INSERT INTO categories (category_name) VALUES('Dairy');
INSERT INTO categories (category_name) VALUES('Grain');
INSERT INTO categories (category_name) VALUES('Canned');
INSERT INTO categories (category_name) VALUES('coldDrinks');
INSERT INTO categories (category_name) VALUES('Dried');
INSERT INTO categories (category_name) VALUES('Toiletries');
INSERT INTO categories (category_name) VALUES('Fruits');
INSERT INTO categories (category_name) VALUES('confectionery');
INSERT INTO categories (category_name) VALUES('Gifts');