INSERT INTO products (product_name, category_id) VALUES('Milk 1l',1);
INSERT INTO products (product_name, category_id) VALUES('Imasi',1);
INSERT INTO products (product_name, category_id) VALUES('Bread',2);
INSERT INTO products (product_name, category_id) VALUES('Iwisa Pap 5kg',2);
INSERT INTO products (product_name, category_id) VALUES('Chakalaka Can',3);
INSERT INTO products (product_name, category_id) VALUES('Gold Dish Vegetable Curry Can',3);
INSERT INTO products (product_name, category_id) VALUES('Fanta 500ml',4);
INSERT INTO products (product_name, category_id) VALUES('Coke 500ml',4);
INSERT INTO products (product_name, category_id) VALUES('Cream Soda 500ml',4);
INSERT INTO products (product_name, category_id) VALUES('Top Class Soy Mince',5);
INSERT INTO products (product_name, category_id) VALUES('Shampoo 1 litre',6);
INSERT INTO products (product_name, category_id) VALUES('Soap Bar',6);
INSERT INTO products (product_name, category_id) VALUES('Valentine Cards',9);
INSERT INTO products (product_name, category_id) VALUES('Rose (plastic)',9);
INSERT INTO products (product_name, category_id) VALUES('Bananas - loose',7);
INSERT INTO products (product_name, category_id) VALUES('Heart Chocolates',8);
INSERT INTO products (product_name, category_id) VALUES('Mixed Sweets 5s',8);
INSERT INTO products (product_name, category_id) VALUES('Apples - loose',7);